### PR TITLE
Add UPC for albums with single UPC

### PR DESCRIPTION
**Pull request by simaofreitas**
Add UPC variable attribution for albums where upc is not an hash

### CODE REVIEW

**Comment by philnash** [comment]
Hi, thanks for this. Could you possibly write a test for this too?

**Comment by simaofreitas** [comment]
Hi!
Sorry for the delay.
I've added the test :)

**Comment by philnash** [comment]
And sorry for my delay, this has been merged now and I've pushed the gem [version 0.3.3](https://rubygems.org/gems/meta-spotify/versions/0.3.3) too.

**Comment by simaofreitas** [comment]
Nice :) Thanks!

**Pull request merged**
