### PR TITLE
Fixed a bad error on some nil returns

### PR DESCRIPTION
**Pull request by amanelis**
Was getting an error in the Track search method as follows. Simply wrote a ternary to catch any nil values from array [].

1.9.2p290 :001 > search = MetaSpotify::Artist.search('foo')
NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]
    from /Users/amanelis/.rvm/gems/ruby-1.9.2-p290@console/gems/meta-spotify-0.1.5/lib/meta-spotify.rb:45:in `search'
    from (irb):1
    from /Users/amanelis/.rvm/gems/ruby-1.9.2-p290@console/gems/railties-3.1.0/lib/rails/commands/console.rb:45:in`start'
    from /Users/amanelis/.rvm/gems/ruby-1.9.2-p290@console/gems/railties-3.1.0/lib/rails/commands/console.rb:8:in `start'
    from /Users/amanelis/.rvm/gems/ruby-1.9.2-p290@console/gems/railties-3.1.0/lib/rails/commands.rb:40:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
1.9.2p290 :002 > exit

### CODE REVIEW

**Comment by philnash** [comment]
Hey,

Thanks for this, would you be able to write a test that this fixes too? As a warning, I'm not sure the gem versions the gem currently requires work. I suggest that it may need to be locked to httparty ~> 0.7.6. I will have a look at making this work (and probably getting rid of Jeweler!) later, but that might help you.

Cheers!

**Comment by amanelis** [comment]
Yeah would be glad to. Also. When searching for an artist either by .lookup or .search. Seems to be no way to return the artists tracks via .tracks method. Please advise! Thanks Phil.

**Comment by philnash** [comment]
Ah, I knew there was an issue with this! Object#try is a Rails extension, not part of core.

I'll update this now, and add the tests. Will look into that other issue as well.

**Comment by philnash** [comment]
Ok, found all the issues!

You're using version 0.1.5 of the gem, which had the wrong version of httparty, please upgrade that to version 0.1.6 and the search methods will work as expected.

As for a .tracks method on artist, that has never existed. The Spotify API doesn't actually make tracks available from the artist response, you actually have to look through an artists albums and make an API call to lookup each album passing an extras parameter of track (or trackdetail, see http://developer.spotify.com/en/metadata-api/lookup/album/ for details) to get the tracks for each album.

**Comment by amanelis** [comment]
Sounds good, thanks for looking this up for me.

**Pull request closed without merging**
